services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow_server
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/mlflow/data
    environment:
      - MLFLOW_TRACKING_URI=sqlite:////mlflow/data/mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=file:///mlflow/data/artifacts
    networks:
      - mlflow_network

networks:
  mlflow_network:
    driver: bridge 